=== 139bercy/format-commande-publique/schémas/xml/contrats-concessions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1">
	<xs:element name="contrat-concession">
		<xs:complexType>
			<xs:all>
				<xs:element name="id">
					<xs:annotation>
						<xs:documentation>L'identifiant de contrat de concession est composé de trois parties:
							- l'année de notification (4 caractères),
							- le numéro d'ordre interne propre à l'acheteur public (1 à 10 caractères alphanumériques)
							- le numéro d'ordre de la modification (deux caractères, 00 si pas de modification, 01 si une modification, etc.)

							Exemples :
							- 201872300 (2018 723 00)
							- 2019000111202 (2019 00001112 02)</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="7"/>
							<xs:maxLength value="16"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="autoriteConcedante">
					<xs:complexType>
						<xs:all>
							<xs:element name="id">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="([0-9]{14,14})"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="nom" type="xs:string"/>

						</xs:all>
					</xs:complexType>
				</xs:element>
				<xs:element name="nature">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="Concession de travaux"/>
							<xs:enumeration value="Concession de service"/>
							<xs:enumeration value="Concession de service public"/>
							<xs:enumeration value="Délégation de service public"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="objet" type="xs:string"/>
				<xs:element name="procedure">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="Procédure négociée ouverte"/>
							<xs:enumeration value="Procédure non négociée ouverte"/>
							<xs:enumeration value="Procédure négociée restreinte"/>
							<xs:enumeration value="Procédure non négociée restreinte"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="lieuExecution">
					<xs:complexType>
						<xs:all>
							<xs:element name="code" type="xs:string"/>
							<xs:element name="typeCode">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="Code postal"/>
										<xs:enumeration value="Code commune"/>
										<xs:enumeration value="Code arrondissement"/>
										<xs:enumeration value="Code canton"/>
										<xs:enumeration value="Code département"/>
										<xs:enumeration value="Code région"/>
										<xs:enumeration value="Code pays"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="nom" type="xs:string"/>

						</xs:all>
					</xs:complexType>
				</xs:element>
				<xs:element name="dureeMois">
					<xs:simpleType>
						<xs:restriction base="xs:integer">
							<xs:minInclusive value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="dateSignature" type="xs:date"/>
				<xs:element name="datePublicationDonnees" type="xs:date"/>
				<xs:element name="dateTransmissionDonneesEtalab" type="xs:date"/>
				<xs:element name="dateDebutExecution" type="xs:date"/>
				<xs:element name="valeurGlobale" type="xs:decimal"/>
				<xs:element name="montantSubventionPublique">
					<xs:simpleType>
						<xs:restriction base="xs:decimal">
							<xs:minInclusive value="0"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="donneesExecution">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="donneesAnnuelles" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:all>
										<xs:element name="datePublicationDonneesExecution" type="xs:date"/>
										<xs:element name="depensesInvestissement">
											<xs:simpleType>
												<xs:restriction base="xs:decimal">
													<xs:minInclusive value="0"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="tarifs">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="tarif" maxOccurs="unbounded">
														<xs:complexType>
															<xs:all>
																<xs:element name="intituleTarif" type="xs:string"/>
																<xs:element name="tarif">
																	<xs:simpleType>
																		<xs:restriction base="xs:decimal">
																			<xs:minInclusive value="0"/>
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>

															</xs:all>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>

									</xs:all>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="concessionnaires">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="concessionnaire" maxOccurs="unbounded">
								<xs:complexType>
									<xs:all>
										<xs:element name="typeIdentifiant">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="SIRET"/>
													<xs:enumeration value="TVA"/>
													<xs:enumeration value="TAHITI"/>
													<xs:enumeration value="RIDET"/>
													<xs:enumeration value="FRWF"/>
													<xs:enumeration value="IREP"/>
													<xs:enumeration value="UE"/>
													<xs:enumeration value="HORS-UE"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="id" type="xs:string"/>
										<xs:element name="denominationSociale" type="xs:string"/>

									</xs:all>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="modifications">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="modification" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:all>
										<xs:element name="objetModification" type="xs:string"/>
										<xs:element name="dateSignatureModification" type="xs:date"/>
										<xs:element name="datePublicationDonneesModification" type="xs:date"/>
										<xs:element name="dureeMois" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:integer">
													<xs:minInclusive value="1"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="valeurGlobale" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:decimal">
													<xs:minInclusive value="0"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>

									</xs:all>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

			</xs:all>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== 139bercy/format-commande-publique/exemples/xml/cc-avec-modifications-données-d-exécution.xml
<?xml version="1.0" encoding="UTF-8"?>
<contrat-concession xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/etalab/format-commande-publique/master/sch%C3%A9mas/xml/contrats-concessions.xsd">
	<id>20010345211202</id>
	<autoriteConcedante>
		<siret>21350238800019</siret>
		<nom>Ville de Millau</nom>
	</autoriteConcedante>
	<nature>Concession de travaux</nature>
	<objet>Construction et exploitation d'un viaduc</objet>
	<procedure>Procédure négociée restreinte</procedure>
	<lieuExecution>
		<code>12145</code>
		<typeCode>Code INSEE commune</typeCode>
		<nom>Millau</nom>
	</lieuExecution>
	<dureeMois>360</dureeMois>
	<dateSignature>2001-02-21</dateSignature>
	<datePublicationDonnees>2001-02-21</datePublicationDonnees>
	<dateTransmissionDonneesEtalab>2007-08-07</dateTransmissionDonneesEtalab>
	<dateDebutExecution>2001-02-21</dateDebutExecution>
	<valeurGlobale>27860000</valeurGlobale>
	<montantSubventionPublique>2987000</montantSubventionPublique>
	<donneesExecution>
		<donneesAnnuelles>
			<datePublicationDonneesExecution>2002-03-30</datePublicationDonneesExecution>
			<depensesInvestissement>658000</depensesInvestissement>
			<tarifs>
				<tarif>
					<intituleTarif>Traversée du viaduc, véhicule léger</intituleTarif>
					<tarif>9.10</tarif>
				</tarif>
				<tarif>
					<intituleTarif>Traversée du viaduc, véhicule lourd</intituleTarif>
					<tarif>14.4</tarif>
				</tarif>
			</tarifs>
		</donneesAnnuelles>
	</donneesExecution>
	<concessionnaires>
		<concessionnaire>
			<typeIdentifiant>SIRET</typeIdentifiant>
			<id>81223113200026</id>
			<denominationSociale>Atlas SAS</denominationSociale>
		</concessionnaire>
	</concessionnaires>
	<modifications>
		<modification>
			<objetModification>Allongement de la durée</objetModification>
			<datePublicationDonneesModification>2002-01-19</datePublicationDonneesModification>
			<dateSignatureModification>2008-07-20</dateSignatureModification>
			<dureeMois>410</dureeMois>
		</modification>
		<modification>
			<objetModification>Allongement de la durée et révision de la valeur globale</objetModification>
			<dateSignatureModification>2008-07-20</dateSignatureModification>
			<datePublicationDonneesModification>2007-06-14</datePublicationDonneesModification>
			<dureeMois>540</dureeMois>
			<valeurGlobale>33890000</valeurGlobale>
		</modification>
	</modifications>
</contrat-concession>
